### PR TITLE
Add sign change event

### PR DESCRIPTION
**Pull request by DevScyu**
Add bukkit sign change event so other plugins can detect when block locker updates the sign.

Fixes https://github.com/MineInAbyss/DeeperWorld/issues/60

### CODE REVIEW

**Comment by rutgerkok** [comment]
Thanks! I will need some time to test this (BlockLocker itself also listens to SignChangeEvent, so I don't know how that would interact), and I'll also modify it so that cancelling the event actually has an effect.

**Comment by DevScyu** [comment]
During my testing, it didn't seem that block locker acted funky in any way

**Comment by rutgerkok** [comment]
I made some changes to the code, so that the SignChangeEvent can now be cancelled. Could you please check if the plugin still works fine in combination with DeeperWorld?

**Comment by c-sig** [comment]
Works fine on my end.
deeperworld-0.3.55-all
blocklocker-1.10.1-SNAPSHOT (BlockLocker-events)

**Comment by DevScyu** [comment]
> I made some changes to the code, so that the SignChangeEvent can now be cancelled. Could you please check if the plugin still works fine in combination with DeeperWorld?

Yup, all works fine still!

**Comment by rutgerkok** [comment]
Thanks, merged!

**Pull request merged**
