### PR TITLE
Retranslated Version.

### PR DESCRIPTION
**Pull request by gregman98**
Please update the file.

### CODE REVIEW

**Comment by rutgerkok** [comment]
Thanks, but to be honest I don't know what these changes mean. What is the reason that these translations would need to replace the original translations of @ibmibmibm ? Are they an improved translation?

**Comment by gregman98** [comment]
Yes, they are improved translation.

**Comment by ibmibmibm** [comment]
There is not much difference from original translation, from my perspective.

**Comment by rutgerkok** [comment]
Great, then I'll merge it. Thanks!

**Pull request merged**
