### PR TITLE
1.16 support

### PR DESCRIPTION
**Pull request by ShiryuDev**

### CODE REVIEW

**Comment by ramdon-person** [comment]
I tested this, and it doesn't seem to work. All that seems to work is the /bl command. When you place a sign on a container it doesn't lock. When you click a sign on a container it doesn't select.

**Comment by MrAmos123** [comment]
Did you just remove the preliminary version check and call it "support"? 😂

**Comment by ShiryuDev** [comment]
its working now

**Comment by rutgerkok** [comment]
Sorry! I took a different approach in 81df566c7c2daf4a31c64bc458f1f0b436555d03 to update the plugin. This implementation adds quite a few conditionals to the class, making it more difficult to maintain. It will also break once the ChatModifier.b field (inevitably) gets renamed.

**Pull request closed without merging**
